import jsPDF from "jspdf";
import { TestRun, ScenarioResult } from "../../types.js";

/**
 * PDF Report Generator
 * Export test runs to PDF format
 */

export class PDFReportGenerator {
  private run: TestRun;

  constructor(run: TestRun) {
    this.run = run;
  }

  /**
   * Generate PDF report
   */
  async generate(): Promise<Buffer> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;

    let yPos = margin;

    // Title
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Test Run Report", margin, yPos);
    yPos += 15;

    // Run ID
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Run ID: ${this.run.id}`, margin, yPos);
    yPos += 8;

    // Suite name
    doc.text(`Suite: ${this.run.suite_name}`, margin, yPos);
    yPos += 8;

    // Status
    doc.text(`Status: ${this.run.status.toUpperCase()}`, margin, yPos);
    yPos += 8;

    // Timestamps
    doc.text(
      `Started: ${new Date(this.run.started_at).toLocaleString()}`,
      margin,
      yPos
    );
    yPos += 8;

    if (this.run.completed_at) {
      doc.text(
        `Completed: ${new Date(this.run.completed_at).toLocaleString()}`,
        margin,
        yPos
      );
      yPos += 15;
    } else {
      yPos += 15;
    }

    // Executive Summary
    yPos = this.addSection(doc, "Executive Summary", yPos);
    yPos = this.addSummaryMetrics(doc, margin, yPos);

    // Scenario Results
    yPos = this.addSection(doc, "Scenario Results", yPos);
    yPos = this.addScenarioResults(doc, margin, yPos, contentWidth);

    // Metrics
    if (this.run.metrics) {
      yPos = this.addSection(doc, "Detailed Metrics", yPos);
      yPos = this.addMetrics(doc, margin, yPos, contentWidth);
    }

    // Add new page if needed
    if (yPos > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      yPos = margin;
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by Agent Testing Suite • Page ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 10
    );

    // Return buffer
    return Buffer.from(doc.output("arraybuffer"));
  }

  /**
   * Add section header
   */
  private addSection(doc: jsPDF, title: string, yPos: number): number {
    // Check page break
    if (yPos > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(title, 20, yPos);

    // Underline
    const width = doc.getTextWidth(title);
    doc.setLineWidth(1);
    doc.line(20, yPos + 2, 20 + width, yPos + 2);

    return yPos + 15;
  }

  /**
   * Add summary metrics
   */
  private addSummaryMetrics(doc: jsPDF, margin: number, yPos: number): number {
    const results = this.run.results;
    const passed = results.filter(r => r.status === "passed").length;
    const failed = results.filter(r => r.status === "failed").length;
    const partial = results.filter(r => r.status === "partial").length;
    const total = results.length;

    const metrics = this.run.metrics;
    const successRate = metrics?.success_rate || 0;

    // Summary card
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    const summary = [
      `Total Scenarios: ${total}`,
      `Passed: ${passed} (${(passed / total * 100).toFixed(1)}%)`,
      `Failed: ${failed} (${(failed / total * 100).toFixed(1)}%)`,
      `Partial: ${partial} (${(partial / total * 100).toFixed(1)}%)`,
      `Success Rate: ${(successRate * 100).toFixed(1)}%`,
      `Total Turns: ${metrics?.total_turns || 0}`,
      `Total Tool Calls: ${metrics?.total_tool_calls || 0}`
    ];

    for (const line of summary) {
      if (yPos > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, margin, yPos);
      yPos += 8;
    }

    return yPos + 10;
  }

  /**
   * Add scenario results table
   */
  private addScenarioResults(
    doc: jsPDF,
    margin: number,
    yPos: number,
    width: number
  ): number {
    const results = this.run.results;

    // Table header
    const colWidths = [width * 0.35, width * 0.15, width * 0.15, width * 0.15, width * 0.2];
    const headers = ["Scenario", "Status", "Turns", "Tools", "Duration (s)"];

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");

    for (let i = 0; i < headers.length; i++) {
      doc.text(headers[i], margin, yPos);
    }

    yPos += 8;

    // Header line
    doc.setLineWidth(0.5);
    doc.line(margin, yPos - 2, margin + width, yPos - 2);

    yPos += 5;

    // Table rows
    doc.setFont("helvetica", "normal");

    for (const result of results) {
      if (yPos > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        yPos = 20;

        // Re-add header
        for (let i = 0; i < headers.length; i++) {
          doc.text(headers[i], margin, yPos);
        }
        yPos += 13;
      }

      let xPos = margin;
      const row = [
        result.scenario_name.substring(0, 30),
        result.status.toUpperCase(),
        result.turn_count.toString(),
        result.tool_calls.toString(),
        (result.duration_ms / 1000).toFixed(1)
      ];

      for (let i = 0; i < row.length; i++) {
        doc.text(row[i], xPos, yPos);
        xPos += colWidths[i];
      }

      yPos += 8;

      // Errors
      if (result.errors.length > 0) {
        doc.setFontSize(8);
        doc.setTextColor(200, 50, 50);

        for (const err of result.errors) {
          if (yPos > doc.internal.pageSize.getHeight() - 30) {
            doc.addPage();
            yPos = 20;
          }

          const truncatedErr = err.substring(0, 80);
          doc.text(`  ERROR: ${truncatedErr}`, margin + 5, yPos);
          yPos += 6;
        }

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
      }

      // Row separator
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPos, margin + width, yPos);
      yPos += 5;
    }

    return yPos + 10;
  }

  /**
   * Add detailed metrics
   */
  private addMetrics(
    doc: jsPDF,
    margin: number,
    yPos: number,
    width: number
  ): number {
    const metrics = this.run.metrics;
    if (!metrics) return yPos;

    // Tool usage
    yPos = this.addSubsection(doc, "Tool Usage", yPos);

    const tools = Object.entries(metrics.tool_usage);
    const sortedTools = tools.sort((a, b) => b[1].call_count - a[1].call_count);

    const colWidths = [width * 0.4, width * 0.15, width * 0.15, width * 0.15, width * 0.15];
    const headers = ["Tool", "Calls", "Success", "Fail", "Avg Duration (ms)"];

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");

    for (let i = 0; i < headers.length; i++) {
      doc.text(headers[i], margin, yPos);
    }

    yPos += 8;

    for (const [toolName, usage] of sortedTools) {
      if (yPos > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        yPos = 20;
      }

      let xPos = margin;
      const row = [
        toolName,
        usage.call_count.toString(),
        usage.success_count.toString(),
        usage.fail_count.toString(),
        usage.avg_duration_ms.toFixed(0)
      ];

      for (let i = 0; i < row.length; i++) {
        doc.text(row[i], xPos, yPos);
        xPos += colWidths[i];
      }

      yPos += 6;
    }

    return yPos + 10;
  }

  /**
   * Add subsection header
   */
  private addSubsection(doc: jsPDF, title: string, yPos: number): number {
    if (yPos > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, 20, yPos);

    return yPos + 10;
  }

  /**
   * Save PDF to file
   */
  async saveToFile(outputPath: string): Promise<void> {
    const buffer = await this.generate();

    const { promises } = await import("node:fs/promises");
    await promises.mkdir(outputPath.split("/").slice(0, -1).join("/"), {
      recursive: true
    });
    await promises.writeFile(outputPath, buffer);

    console.log(`✅ PDF report saved to ${outputPath}`);
  }
}
